import { z } from 'zod';
import { api,route,empty,id,text,money,geo,limit,admins,operators,officers,user,param,actor,key } from '../../apiRegistry';
import * as authentication from '../../modules/auth/service';
import * as users from '../../modules/users/service';
import * as vehicles from '../../modules/vehicles/service';
import * as parking from '../../modules/parking/service';
import * as sessions from '../../modules/sessions/service';
import * as wallet from '../../modules/wallet/service';
import * as roads from '../../modules/roads/service';
import * as trust from '../../modules/trust/service';
import * as violations from '../../modules/violations/service';
import * as notifications from '../../modules/notifications/service';
import * as admin from '../../modules/admin/service';
import { routingService } from '../../modules/routing/service';
route('get','/admin/users',empty,()=>admin.users(),admins);
route('patch','/admin/users/:id',z.object({role:z.enum(['USER','ADMIN','PARKING_OPERATOR','ENFORCEMENT_OFFICER']).optional(),status:z.enum(['ACTIVE','SUSPENDED']).optional()}).strict(),(r,b)=>admin.role(actor(r),param(r),b),admins);
route('get','/admin/parking-zones',empty,r=>admin.zones(actor(r)),operators);
const zone=z.object({operatorId:id,code:text,name:text,nameAr:text,city:text,cityAr:text,description:z.string().max(2000).optional(),address:text.optional(),latitude:geo.shape.latitude,longitude:geo.shape.longitude,kind:z.enum(['street','garage','lot','private']),capacity:z.number().int().positive().optional(),defaultMode:z.enum(['start_stop','prepaid']),supportedModes:z.array(z.enum(['start_stop','prepaid'])).min(1),supportedEntryMethods:z.array(z.enum(['gps','qr','zone_code','anpr','manual'])).min(1),active:z.boolean().optional()}).strict();
route('post','/admin/parking-zones',zone,(r,b)=>admin.createZone(actor(r),b),admins);
route('patch','/admin/parking-zones/:id',zone.omit({operatorId:true}).partial(),(r,b)=>admin.patchZone(actor(r),param(r),b),operators);
route('post','/admin/parking-zones/:id/tariffs',z.object({name:text,hourlyRate:money,incrementMinutes:z.number().int().min(1).max(60),freeMinutes:z.number().int().min(0).max(1440),minimumCharge:money,dailyCap:money.optional(),maxStayMinutes:z.number().int().min(15).max(1440).optional(),validFrom:z.iso.datetime(),validTo:z.iso.datetime().optional()}).strict(),(r,b)=>admin.tariff(actor(r),param(r),b),operators);
const hour=z.object({weekday:z.number().int().min(0).max(6),opensAt:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),closesAt:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),closed:z.boolean()}).strict();
route('patch','/admin/parking-zones/:id/hours',z.object({hours:z.array(hour).length(7).refine(a=>new Set(a.map(h=>h.weekday)).size===7)}).strict(),(r,b)=>admin.hours(actor(r),param(r),b.hours),operators);
route('post','/admin/parking-zones/:id/availability',z.object({availability:z.enum(['available','limited','full','unknown']),availableSpaces:z.number().int().nonnegative().optional(),occupiedSpaces:z.number().int().nonnegative().optional(),source:z.enum(['ADMIN','OPERATOR','SENSOR','ANPR']),confidence:z.number().min(0).max(1)}).strict(),(r,b)=>admin.availability(actor(r),param(r),b),operators);
route('get','/admin/road-reports',empty,()=>admin.reports(),admins);
route('patch','/admin/road-reports/:id',z.object({hidden:z.boolean()}).strict(),(r,b)=>admin.moderate(actor(r),param(r),b.hidden),admins);
route('get','/admin/violations',empty,()=>admin.violations(),officers);
route('post','/admin/violations',z.object({vehicleId:id,type:z.enum(['no_active_parking','expired_parking','wrong_zone','no_permit','obstruction','disabled_bay']),amount:money.min(1),parkingZoneId:id.optional(),locationName:text,locationNameAr:text,latitude:geo.shape.latitude,longitude:geo.shape.longitude,dueAt:z.iso.datetime(),reason:z.string().min(1).max(2000),reasonAr:z.string().min(1).max(2000),issuingAuthority:text,issuingAuthorityAr:text}).strict(),(r,b)=>admin.issueViolation(actor(r),{...b,plateNumber:''}),officers);
route('post','/admin/violations/:id/evidence',z.object({detectedPlate:text,detectionSource:z.enum(['anpr_vehicle','fixed_camera','inspector','sensor']),firstDetectionAt:z.iso.datetime(),latitude:geo.shape.latitude,longitude:geo.shape.longitude,uploadIds:z.array(id).min(1).max(5)}).strict(),(r,b)=>admin.addEvidence(actor(r),param(r),b),officers);
route('patch','/admin/appeals/:id',z.object({status:z.enum(['under_review','approved','rejected','more_info']),decisionNote:z.string().min(1).max(2000)}).strict(),(r,b)=>admin.decideAppeal(actor(r),param(r),b),admins);
route('post','/admin/permits',z.object({userId:id,vehicleId:id,type:z.enum(['resident','disabled','business','staff']),zoneIds:z.array(id).max(100),validFrom:z.iso.datetime(),validTo:z.iso.datetime(),status:z.enum(['active','pending']),issuer:text}).strict().refine(b=>new Date(b.validTo)>new Date(b.validFrom)),(r,b)=>admin.permit(actor(r),b),operators);
route('patch','/admin/permits/:id/revoke',empty,r=>admin.revokePermit(actor(r),param(r)),operators);
route('post','/admin/users/:id/wallet-adjustments',z.object({amount:z.number().int().min(-10000000).max(10000000),reason:z.string().min(5).max(500)}).strict(),(r,b)=>admin.adjustment(actor(r),param(r),b.amount,b.reason,key(r)),admins);
route('get','/admin/audit-logs',empty,()=>admin.auditLogs(),admins);
route('get','/admin/operators',empty,()=>admin.operators(),admins);
route('post','/admin/operators',z.object({name:text,type:z.enum(['municipality','mall','hospital','garage'])}).strict(),(r,b)=>admin.createOperator(actor(r),b),admins);
route('post','/admin/operators/:id/users',z.object({userId:id}).strict(),(r,b)=>admin.assignOperator(actor(r),param(r),b.userId),admins);
route('post','/admin/vehicles/:id/users',z.object({userId:id,role:z.enum(['owner','driver','manager'])}).strict(),(r,b)=>admin.shareVehicle(actor(r),param(r),b),admins);

route('post','/admin/transactions/:id/refund',z.object({reason:z.string().min(5).max(500)}).strict(),(r,b)=>admin.refund(actor(r),param(r),b.reason,key(r)),admins);
route('get','/admin/appeals',empty,()=>admin.appeals(),admins);
