import type { Role,Prisma } from '@prisma/client';
import { db,atomic,json,type Tx } from '../../database/client';
import { assert,requireValue } from '../../utils/errors';
import { notify } from '../notifications/service';
import { post } from '../wallet/ledger';
import { idempotent } from '../../utils/idempotency';
import { event } from '../../realtime/outbox';
export interface Actor {userId:string;role:Role;ip?:string;userAgent?:string}
async function audit(tx:Tx,a:Actor,action:string,resourceType:string,resourceId:string,before:unknown,after:unknown){await tx.auditLog.create({data:{actorUserId:a.userId,action,resourceType,resourceId,before:before==null?undefined:json(before),after:after==null?undefined:json(after),ip:a.ip,userAgent:a.userAgent}});}
export async function zonePermission(tx:Tx,a:Actor,zoneId:string){const zone=requireValue(await tx.parkingZone.findUnique({where:{id:zoneId}}));if(a.role!=='ADMIN')assert(await tx.operatorUser.findUnique({where:{operatorId_userId:{operatorId:zone.operatorId,userId:a.userId}}}),'FORBIDDEN','You do not manage this zone',403);return zone;}
export async function users(){return db.user.findMany({take:200,orderBy:{createdAt:'desc'},select:{id:true,phone:true,fullName:true,role:true,status:true,createdAt:true}});}
export async function zones(a:Actor){return db.parkingZone.findMany({where:a.role==='ADMIN'?{}:{operator:{users:{some:{userId:a.userId}}}},take:200,include:{tariffs:true,operatingHours:true}});}
export async function createZone(a:Actor,input:Prisma.ParkingZoneUncheckedCreateInput){return atomic(async tx=>{const z=await tx.parkingZone.create({data:input});await audit(tx,a,'create','parking-zone',z.id,null,z);return z;});}
export async function patchZone(a:Actor,id:string,input:Prisma.ParkingZoneUpdateInput){return atomic(async tx=>{const before=await zonePermission(tx,a,id);const after=await tx.parkingZone.update({where:{id},data:input});await audit(tx,a,'update','parking-zone',id,before,after);return after;});}
export async function tariff(a:Actor,zoneId:string,input:Omit<Prisma.ParkingTariffUncheckedCreateInput,'zoneId'>){return atomic(async tx=>{await zonePermission(tx,a,zoneId);const effective=new Date(input.validFrom);assert(effective.getTime()>=Date.now()-60000,'VALIDATION','Tariffs cannot be backdated');await tx.parkingTariff.updateMany({where:{zoneId,validTo:null},data:{validTo:effective}});const t=await tx.parkingTariff.create({data:{...input,zoneId}});await audit(tx,a,'create','tariff',t.id,null,t);return t;});}
export async function hours(a:Actor,zoneId:string,rows:{weekday:number;opensAt:string;closesAt:string;closed:boolean}[]){return atomic(async tx=>{await zonePermission(tx,a,zoneId);const before=await tx.operatingHour.findMany({where:{zoneId}});await tx.operatingHour.deleteMany({where:{zoneId}});await tx.operatingHour.createMany({data:rows.map(r=>({...r,zoneId}))});await audit(tx,a,'update','operating-hours',zoneId,before,rows);return rows;});}
export async function availability(a:Actor,zoneId:string,input:{availability:'available'|'limited'|'full'|'unknown';availableSpaces?:number;occupiedSpaces?:number;source:string;confidence:number}){return atomic(async tx=>{await zonePermission(tx,a,zoneId);const s=await tx.availabilitySnapshot.create({data:{zoneId,...input}});await audit(tx,a,'create','availability',s.id,null,s);await event(tx,'parking.availability.updated',{zoneId});return s;});}
export async function reports(){return db.roadReport.findMany({take:200,orderBy:{reportedAt:'desc'}});}
export async function moderate(a:Actor,id:string,hidden:boolean){return atomic(async tx=>{const before=await tx.roadReport.findUniqueOrThrow({where:{id}});const after=await tx.roadReport.update({where:{id},data:{hidden}});if(hidden)await tx.pointsEntry.updateMany({where:{roadReportId:id},data:{state:'revoked'}});await audit(tx,a,'moderate','road-report',id,before,after);await event(tx,'checkpoint.updated',{checkpointId:after.checkpointId});return after;});}
export async function violations(){return db.violation.findMany({take:200,orderBy:{issuedAt:'desc'}});}
export async function issueViolation(a:Actor,input:Prisma.ViolationUncheckedCreateInput){return atomic(async tx=>{
 const vehicle=requireValue(await tx.vehicle.findUnique({where:{id:input.vehicleId}}));const v=await tx.violation.create({data:{...input,plateNumber:vehicle.plateNumber}});
 const links=await tx.userVehicle.findMany({where:{vehicleId:vehicle.id,unlinkedAt:null}});for(const l of links)await notify(tx,l.userId,'violation_issued','New vehicle violation','?????? ????? ???????',v.reason,v.reasonAr,`/violations/${v.id}`);
 await audit(tx,a,'create','violation',v.id,null,v);return v;});}
export async function addEvidence(a:Actor,id:string,input:{detectedPlate:string;detectionSource:string;firstDetectionAt:string;latitude:number;longitude:number;uploadIds:string[]}){return atomic(async tx=>{requireValue(await tx.violation.findUnique({where:{id}}));const {uploadIds,...fields}=input;const owned=await tx.upload.count({where:{id:{in:uploadIds},userId:a.userId}});assert(owned===new Set(uploadIds).size,'FORBIDDEN','Attachments must be uploaded by you',403);const e=await tx.violationEvidence.create({data:{violationId:id,...fields,photos:{create:uploadIds.map((uploadId,i)=>({uploadId,kind:i===0?'vehicle':'additional'}))}}});await audit(tx,a,'create','violation-evidence',e.id,null,e);return e;});}
export async function decideAppeal(a:Actor,id:string,input:{status:'under_review'|'approved'|'rejected'|'more_info';decisionNote:string}){return atomic(async tx=>{const before=await tx.appeal.findUniqueOrThrow({where:{id}});const after=await tx.appeal.update({where:{id},data:input});if(['approved','rejected'].includes(input.status))await tx.violation.update({where:{id:after.violationId},data:{status:input.status==='approved'?'cancelled':'unpaid'}});await notify(tx,after.userId,'appeal_updated','Appeal updated','????? ????????',input.decisionNote,input.decisionNote,`/violations/${after.violationId}`);await audit(tx,a,'decide','appeal',id,before,after);return after;});}
export async function permit(a:Actor,input:{userId:string;vehicleId:string;type:string;zoneIds:string[];validFrom:string;validTo:string;status:'active'|'pending';issuer:string}){return atomic(async tx=>{if(a.role!=='ADMIN'){assert(input.zoneIds.length,'FORBIDDEN','Operator permits must specify zones',403);for(const zoneId of input.zoneIds)await zonePermission(tx,a,zoneId);}assert(await tx.userVehicle.findFirst({where:{userId:input.userId,vehicleId:input.vehicleId,unlinkedAt:null}}),'VALIDATION','Vehicle must be linked to this user');const {zoneIds,...data}=input;const p=await tx.permit.create({data:{...data,zones:{create:zoneIds.map(zoneId=>({zoneId}))}}});await audit(tx,a,'create','permit',p.id,null,p);return p;});}
export async function revokePermit(a:Actor,id:string){return atomic(async tx=>{const p=await tx.permit.findUniqueOrThrow({where:{id},include:{zones:true}});if(a.role!=='ADMIN'){assert(p.zones.length,'FORBIDDEN','Only admin can revoke a global permit',403);for(const z of p.zones)await zonePermission(tx,a,z.zoneId);}const result=await tx.permit.update({where:{id},data:{status:'revoked'}});await audit(tx,a,'revoke','permit',id,p,result);return result;});}
export async function role(a:Actor,id:string,input:{role?:Role;status?:'ACTIVE'|'SUSPENDED'}){return atomic(async tx=>{assert(id!==a.userId,'VALIDATION','Cannot change your own permissions');const before=await tx.user.findUniqueOrThrow({where:{id}});const after=await tx.user.update({where:{id},data:input});await tx.refreshToken.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date()}});await audit(tx,a,'permissions','user',id,{role:before.role,status:before.status},{role:after.role,status:after.status});return {id,role:after.role,status:after.status};});}
export async function adjustment(a:Actor,userId:string,amount:number,reason:string,key:string){return idempotent(a.userId,`adjust:${userId}`,key,{amount,reason},async tx=>{const t=await post(tx,userId,{amount,type:'adjustment',title:reason,titleAr:reason});await audit(tx,a,'adjust','wallet',t.walletId,null,t);return t;});}
export async function auditLogs(){return db.auditLog.findMany({take:200,orderBy:{createdAt:'desc'}});}
export async function operators(){return db.parkingOperator.findMany({include:{users:true}});}
export async function createOperator(a:Actor,input:{name:string;type:string}){return atomic(async tx=>{const o=await tx.parkingOperator.create({data:input});await audit(tx,a,'create','operator',o.id,null,o);return o;});}
export async function assignOperator(a:Actor,operatorId:string,userId:string){return atomic(async tx=>{const link=await tx.operatorUser.upsert({where:{operatorId_userId:{operatorId,userId}},create:{operatorId,userId},update:{}});await audit(tx,a,'assign','operator-user',operatorId,null,link);return link;});}
export async function shareVehicle(a:Actor,vehicleId:string,input:{userId:string;role:string}){return atomic(async tx=>{const link=await tx.userVehicle.upsert({where:{userId_vehicleId:{userId:input.userId,vehicleId}},create:{...input,vehicleId},update:{role:input.role,unlinkedAt:null}});await audit(tx,a,'grant','vehicle-link',link.id,null,link);return link;});}

export async function refund(a:Actor,id:string,reason:string,key:string){return idempotent(a.userId,`refund:${id}`,key,{reason},async tx=>{
 const original=requireValue(await tx.walletTransaction.findUnique({where:{id},include:{wallet:true}}));
 assert(original.status==='completed'&&original.amount<0,'INVALID_REFUND','Only a completed debit can be refunded');
 const reference=`refund-${id}`;const existing=await tx.walletTransaction.findUnique({where:{reference}});if(existing)return existing;
 const entry=await post(tx,original.wallet.userId,{amount:-original.amount,type:'refund',title:reason,titleAr:reason,reference});await audit(tx,a,'refund','transaction',id,original,entry);return entry;
 });}
export async function appeals(){return db.appeal.findMany({take:200,orderBy:{submittedAt:'desc'}});}
