import { z } from 'zod';
import { api,route,empty,id,text,money,geo,limit,admins,operators,officers,user,param,actor,key } from '../../apiRegistry';
import * as authentication from '../../modules/auth/service';
import * as users from '../../modules/users/service';
import * as vehicles from '../../modules/vehicles/service';
import * as parking from '../../modules/parking/service';
import * as sessions from '../../modules/sessions/service';
import * as wallet from '../../modules/wallet/service';
import * as roads from '../../modules/roads/service';
import * as trust from '../../modules/trust/service';
import * as violations from '../../modules/violations/service';
import * as notifications from '../../modules/notifications/service';
import * as admin from '../../modules/admin/service';
import { routingService } from '../../modules/routing/service';
const vehicle=z.object({plateNumber:z.string().regex(/^[0-9 -]{5,16}$/),type:z.enum(['private','commercial','taxi','motorcycle']),make:text.optional(),model:text.optional(),year:z.number().int().min(1900).max(2100).optional(),color:text.optional(),colorHex:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),nickname:text.optional(),region:z.enum(['PS','IL']).optional()}).strict();
route('get','/vehicles',empty,r=>vehicles.list(user(r)));
route('post','/vehicles',vehicle,(r,b)=>vehicles.create(user(r),b));
route('get','/vehicles/:id',empty,r=>vehicles.get(user(r),param(r)));
route('patch','/vehicles/:id',vehicle.partial(),(r,b)=>vehicles.update(user(r),param(r),b));
route('delete','/vehicles/:id',empty,r=>vehicles.unlink(user(r),param(r)));
route('patch','/vehicles/:id/default',empty,r=>vehicles.setDefault(user(r),param(r)));
route('get','/vehicles/:id/permits',empty,r=>vehicles.permits(user(r),param(r)));
