import { z } from 'zod';
import { api,route,empty,id,text,money,geo,limit,admins,operators,officers,user,param,actor,key } from '../../apiRegistry';
import * as authentication from '../../modules/auth/service';
import * as users from '../../modules/users/service';
import * as vehicles from '../../modules/vehicles/service';
import * as parking from '../../modules/parking/service';
import * as sessions from '../../modules/sessions/service';
import * as wallet from '../../modules/wallet/service';
import * as roads from '../../modules/roads/service';
import * as trust from '../../modules/trust/service';
import * as violations from '../../modules/violations/service';
import * as notifications from '../../modules/notifications/service';
import * as admin from '../../modules/admin/service';
import { routingService } from '../../modules/routing/service';
const nearby=z.object({lat:z.coerce.number().min(-90).max(90),lng:z.coerce.number().min(-180).max(180),radius:z.coerce.number().min(1).max(100000).optional()}).strict();
route('get','/parking/zones/nearby',nearby,(_r,b)=>parking.listZones(b));
route('get','/parking/zones/code/:code',empty,r=>parking.byCode(param(r,'code')));
route('get','/parking/zones',nearby.partial().extend({search:z.string().max(200).optional()}),(_r,b)=>parking.listZones(b));
route('get','/parking/zones/:id',empty,r=>parking.getZone(param(r)));
route('get','/parking/facilities/:id',empty,r=>parking.facility(param(r)));
route('post','/parking/sessions',z.object({vehicleId:id,zoneId:id,mode:z.enum(['start_stop','prepaid']),durationMinutes:z.number().int().min(15).max(1440).optional(),entryMethod:z.enum(['gps','qr','zone_code','anpr','manual'])}).strict(),(r,b)=>sessions.start(user(r),b,key(r)));
route('get','/parking/sessions/active',z.object({vehicleId:id.optional()}).strict(),(r,b)=>sessions.list(user(r),{...b,active:true}));
route('get','/parking/sessions',z.object({vehicleId:id.optional(),limit}).strict(),(r,b)=>sessions.list(user(r),b));
route('get','/parking/sessions/:id',empty,r=>sessions.get(user(r),param(r)));
route('post','/parking/sessions/:id/stop',empty,r=>sessions.stop(user(r),param(r),key(r)));
route('post','/parking/sessions/:id/settle',empty,r=>sessions.settle(user(r),param(r),key(r)));
route('post','/parking/sessions/:id/extend',z.object({additionalMinutes:z.number().int().min(15).max(1440)}).strict(),(r,b)=>sessions.extend(user(r),param(r),b.additionalMinutes,key(r)));
