import { z } from 'zod';
import { api,route,empty,id,text,money,geo,limit,admins,operators,officers,user,param,actor,key } from '../../apiRegistry';
import * as authentication from '../../modules/auth/service';
import * as users from '../../modules/users/service';
import * as vehicles from '../../modules/vehicles/service';
import * as parking from '../../modules/parking/service';
import * as sessions from '../../modules/sessions/service';
import * as wallet from '../../modules/wallet/service';
import * as roads from '../../modules/roads/service';
import * as trust from '../../modules/trust/service';
import * as violations from '../../modules/violations/service';
import * as notifications from '../../modules/notifications/service';
import * as admin from '../../modules/admin/service';
import { routingService } from '../../modules/routing/service';
import multer from 'multer';
import { auth } from '../../middleware/auth';
import { assert } from '../../utils/errors';
route('get','/violations',z.object({vehicleId:id.optional()}).strict(),(r,b)=>violations.list(user(r),b.vehicleId));
route('get','/violations/:id',empty,r=>violations.get(user(r),param(r)));
route('get','/violations/:id/evidence',empty,r=>violations.evidence(user(r),param(r)));
route('post','/violations/:id/pay',empty,r=>violations.pay(user(r),param(r),key(r)));
route('post','/violations/:id/appeals',z.object({reason:z.enum(['paid_not_recognized','wrong_vehicle','wrong_location','special_permit','technical_issue','other']),notes:z.string().min(10).max(5000),attachmentIds:z.array(id).max(5)}).strict(),(r,b)=>violations.appeal(user(r),param(r),b));
route('get','/appeals/:id',empty,r=>violations.getAppeal(user(r),param(r)));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:0}});
api.post('/uploads',auth,upload.single('file'),async(r,res,next)=>{try{assert(r.file,'INVALID_UPLOAD','Attach a file');res.json(await violations.upload(user(r),r.file));}catch(e){next(e);}});
