export { api,paths } from './apiRegistry';
import './modules/auth/routes';
import './modules/vehicles/routes';
import './modules/parking/routes';
import './modules/wallet/routes';
import './modules/roads/routes';
import './modules/roadReports/routes';
import './modules/evStations/routes';
import './modules/reservations/routes';
import './modules/violations/routes';
import './modules/notifications/routes';
import './modules/admin/routes';
import './modules/operator/routes';
import './modules/forecasting/routes';
import './modules/management/routes';
import './modules/appConfig/routes';
import './modules/vehicleVerification/routes';
