import { z } from 'zod';
import { api,route,empty,id,text,money,geo,limit,admins,operators,officers,user,param,actor,key } from '../../apiRegistry';
import * as authentication from '../../modules/auth/service';
import * as users from '../../modules/users/service';
import * as vehicles from '../../modules/vehicles/service';
import * as parking from '../../modules/parking/service';
import * as sessions from '../../modules/sessions/service';
import * as wallet from '../../modules/wallet/service';
import * as roads from '../../modules/roads/service';
import * as trust from '../../modules/trust/service';
import * as violations from '../../modules/violations/service';
import * as notifications from '../../modules/notifications/service';
import * as admin from '../../modules/admin/service';
import { routingService } from '../../modules/routing/service';
route('get','/notifications',empty,r=>notifications.list(user(r)));
route('get','/notifications/unread-count',empty,r=>notifications.unread(user(r)));
route('patch','/notifications/read-all',empty,r=>notifications.read(user(r)));
route('patch','/notifications/:id/read',empty,r=>notifications.read(user(r),param(r)));
route('post','/notifications/device-tokens',z.object({token:z.string().min(10).max(4096),platform:z.enum(['ios','android','web']),provider:z.enum(['fcm','expo'])}).strict(),(r,b)=>notifications.register(user(r),b));
route('delete','/notifications/device-tokens',z.object({token:z.string().min(10).max(4096)}).strict(),(r,b)=>notifications.unregister(user(r),b.token));
